name: inline_notifier
description: "Simple inline notifier. Simplify your code with inline notifier on diferent pages."
version: 1.0.1
repository: https://github.com/hacp0012/inline_notifier
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - valuenotifier
  - changenotifier
  - updatenotifier
  - notifier
  - notify
